services:
  pgsql:
    image: 'postgres:16'
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE:-mercardo_aberto}'
      POSTGRES_USER: '${DB_USERNAME:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - './.docker/postgres:/var/lib/postgresql/data'
    networks:
      - ljp
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    user: root
    depends_on:
      - pgsql
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@postgres.com'
      PGADMIN_DEFAULT_PASSWORD: '${DB_PASSWORD:-password}'
    ports:
      - 8081:80
    volumes:
      - './.docker/pgadmin:/var/lib/pgadmin'
    networks:
      - ljp

networks:
  ljp:
    driver: bridge
volumes:
  ljp-pgsql:
    driver: local
