name: Setup and Tests

on:
  pull_request:
    branches: [develop]

jobs:
  setup-and-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: mercado_aberto
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, pdo_pgsql
          tools: composer:v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install npm dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate

      - name: Seed database
        run: php artisan db:seed

      - name: Start frontend
        run: LARAVEL_BYPASS_ENV_CHECK=1 npm run dev &

      - name: Start backend
        run: php artisan serve &

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npm run test

